### ISSUE TITLE
Exit code 134

### ISSUE THREAD

**Issue by RachellyN** [theislab/scCODA#46] opened 2022-01-11 16:14 UTC
Hi,
I ran scCODA the following way:
```
counts_per_sample = pd.read_csv("counts2.csv")
counts_adata = dat.from_pandas(counts_per_sample, covariate_columns=['Condition'])
model = mod.CompositionalAnalysis(counts_adata, formula=f"C('Condition', Treatment('ctl'))", reference_cell_type='automatic')
sim_results = model.sample_hmc()
sim_results.summary()
```

The execution was halted due to Exit code 134. Full output and input files are attached.
Thanks,
Rachelly.

[counts2.csv](https://github.com/theislab/scCODA/files/7848129/counts2.csv)
[output2.txt.txt](https://github.com/theislab/scCODA/files/7848130/output2.txt.txt)

**Comment by johannesostner** [comment] 2022-01-12 08:01
Hi Rachelly,
thanks for reporting this error!

This seems to be an issue related to tensorflow. Could you please provide the version numbers of your tensorflow, tensorflwo-probability and scCODA installations?
Also, are you trying to run scCODA on a cluster? The error `resource temporarily unavailable` could also be related to that.

**Comment by RachellyN** [comment] 2022-01-15 15:20
Hi johannesostner,
Here are my software versions:
scCODA: 0.1.4
tensorflow: 2.6.0
tensorflow-probability: 0.14.0

And yes, I am using a cluster.

**Comment by johannesostner** [comment] 2022-01-17 07:30
I am unsure whether this is the cause of the error, but the package versions you use are not tested with scCODA. The package is tested against `tensorflow 2.4` and `tensorflow-probability 2.6`. There was an oversight on our side in the 0.1.4 version of scCODA, where the latest versions of both packages were always installed, instead of the recommended ones.
Please try downgrading these two packages and upgrading scCODA to 0.1.6. 

I hope that this fixes your problem!

**Comment by RachellyN** [comment] 2022-01-23 03:07
Thank you again. 
After upgrading to scCODA 0.016, tensorflow 2.4 and tensorflow-probability 0.12 (there is no version 2.6), this error message is gone!

**Comment by Zethson** [comment] 2022-01-26 10:54
@johannesostner pinning Tensorflow to >=2.4 < 2.6 solves the issue, but is rather restrictive for environments which use more tools than sccoda. Would it be possible to identify and fix the root cause?

**Comment by johannesostner** [comment] 2022-05-04 13:51
The latest version of `scCODA` (0.1.7) are compatible with the latest tensorflow (2.8.0) and tensorflow-probability (0.16.0) versions. I could not reproduce the error described here, though. Closing this for now.

**Closed by johannesostner** 2022-05-04 13:51 UTC
